# scrutinizer-ci.com configuration
imports:
  - php
filter:
  excluded_paths:
    - build/
    - tmp/
    - vendor/
    - tools/doctum-config.php
checks:
  php: true
tools:
  external_code_coverage:
    runs: 2 # php 8.x versions
    timeout: 480 # 8 min
build:
  nodes:
    analysis:
      environment:
        php: 8.2
      dependencies:
        before:
          - composer install
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
